# Generated by Django 3.2.4 on 2021-07-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0009_youtube'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtube',
        ),
    ]
