# Generated by Django 3.2.4 on 2021-08-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0010_delete_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='img',
            new_name='gimg',
        ),
    ]
