# Generated by Django 3.2.4 on 2021-08-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0011_rename_img_galleryimage_gimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='gimg',
            new_name='img',
        ),
    ]
