# Generated by Django 3.2.4 on 2021-08-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0012_rename_gimg_galleryimage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='Gallery',
            new_name='gallery',
        ),
    ]
