# Generated by Django 3.2.4 on 2021-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0017_auto_20210810_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('detaile', models.TextField()),
                ('img', models.ImageField(upload_to='Trainer/')),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='img',
            field=models.ImageField(null=True, upload_to='subs/'),
        ),
    ]
