# Generated by Django 3.2.7 on 2021-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0021_auto_20211004_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSetting',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='salary',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pinterest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
