# Generated by Django 3.2.7 on 2021-10-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0023_appsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSetting',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='ans',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='quest',
            new_name='question',
        ),
    ]
