# Generated by Django 3.2.7 on 2021-10-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0024_auto_20211005_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answers',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='quest',
        ),
    ]
