# Generated by Django 3.2.7 on 2021-10-05 16:43

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0025_auto_20211005_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
