# Generated by Django 3.2.8 on 2021-10-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0027_rename_videos_youtube_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
