# Generated by Django 3.2.8 on 2021-10-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0029_students_studentsachivement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='StudentsAchivement',
        ),
    ]
