# Generated by Django 3.2.8 on 2021-12-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0030_auto_20211016_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('achievement_detail', models.TextField()),
                ('img', models.ImageField(upload_to='students/')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name_plural': 'YouTube'},
        ),
        migrations.CreateModel(
            name='StudentsAchivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('alt_text', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='student_achivements/')),
                ('Students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFCapp.students')),
            ],
        ),
    ]
