# Generated by Django 3.2.8 on 2021-12-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0031_auto_20211223_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='pinterest',
            new_name='instagram',
        ),
    ]
