# Generated by Django 3.2.8 on 2021-12-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0032_rename_pinterest_students_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='achievement_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='studentsachivement',
            old_name='Students',
            new_name='students',
        ),
    ]
