# Generated by Django 3.2.8 on 2021-12-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0033_auto_20211223_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentsachivement',
            options={'verbose_name_plural': 'Students Achivement'},
        ),
        migrations.AddField(
            model_name='students',
            name='alt_text',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
