# Generated by Django 3.2.8 on 2021-12-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0034_auto_20211223_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='studentsachivement',
            old_name='img',
            new_name='image',
        ),
    ]
