# Generated by Django 3.2.8 on 2022-01-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFCapp', '0035_auto_20211223_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsachivement',
            name='students',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='StudentsAchivement',
        ),
    ]
