"""
Django settings for NFCMMAClub project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = BASE_DIR / 'template'
STATIC_FILES = BASE_DIR / 'static'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wonsxvwizdw-w6+97i00cj*xb#a15diy(q-7b=(4i=o)js0f2)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'channels',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'NFCapp',
    'embed_video',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NFCMMAClub.urls'

TEMPLATES = [
    {
        'BACKEND' :'django.template.backends.django.DjangoTemplates',
        'DIRS' :[TEMPLATES_DIR, ],
        'APP_DIRS' :True,
        'OPTIONS' :{
            'context_processors' :[
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'NFCMMAClub.wsgi.application'
ASGI_APPLICATION = 'NFCMMAClub.asgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default' :{
        'ENGINE' :'django.db.backends.postgresql_psycopg2',
        'NAME' :'postgres',
        'USER' :'postgres',
        'PASSWORD' :'Fqthedeveloper',
        'HOST' :'127.0.0.1',
        'POST' :'5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME' :'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME' :'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME' :'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME' :'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title" :"NFCMMAClub Admin",
    "site_header" :"NFCMMA Admin",
    "order_with_respect_to" :["auth", "NFCapp.banners", "NFCapp.service", "NFCapp.enquiry", "NFCapp.gallery",
                              "NFCapp.GalleryImage", "NFCapp.Page", ],
}

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

CHANNEL_LAYERS = {
    "default" :{
        "BACKEND" :"channels_redis.core.RedisChannelLayer",
        "CONFIG" :{
            "hosts" :[("127.0.0.1", 6379)],

        },
    },
}
